# Generated by Django 5.1.4 on 2025-01-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('due_date', models.DateTimeField(verbose_name='Bitiş Tarihi')),
                ('priority', models.IntegerField(default=0, verbose_name='Öncelik')),
                ('completed', models.BooleanField(default=False, verbose_name='Tamamlandı')),
            ],
            options={
                'verbose_name': 'Görev',
                'verbose_name_plural': 'Görevler',
                'ordering': ['due_date', '-priority'],
            },
        ),
    ]
