# Generated by Django 5.1.4 on 2025-01-14 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_hours', models.IntegerField(default=8, verbose_name='Günlük Çalışma Saati')),
                ('sleep_hours', models.IntegerField(default=8, verbose_name='Günlük Uyku Saati')),
                ('preferred_task_time', models.CharField(default='Sabah', max_length=50, verbose_name='Tercih Edilen Görev Zamanı')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
