# Generated by Django 5.1.4 on 2025-06-05 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_tag_task_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Kategori Adı"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6", max_length=7, verbose_name="Renk Kodu"
                    ),
                ),
                (
                    "icon",
                    models.CharField(default="📋", max_length=50, verbose_name="İkon"),
                ),
            ],
            options={
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategoriler",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="actual_duration",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Gerçek Süre"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="task_attachments/",
                verbose_name="Dosya Eki",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="end_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Bitiş Zamanı"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="estimated_duration",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Tahmini Süre"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notlar"),
        ),
        migrations.AddField(
            model_name="task",
            name="start_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Başlangıç Zamanı"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Beklemede"),
                    ("in_progress", "Devam Ediyor"),
                    ("completed", "Tamamlandı"),
                    ("cancelled", "İptal Edildi"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "Yüksek"), (2, "Orta"), (3, "Düşük")],
                default=2,
                verbose_name="Öncelik",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tasks.category",
                verbose_name="Kategori",
            ),
        ),
        migrations.CreateModel(
            name="PomodoroSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "duration",
                    models.IntegerField(default=25, verbose_name="Süre (dakika)"),
                ),
                ("completed", models.BooleanField(default=False)),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pomodoro Oturumu",
                "verbose_name_plural": "Pomodoro Oturumları",
            },
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Yorum")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Görev Yorumu",
                "verbose_name_plural": "Görev Yorumları",
                "ordering": ["-created_at"],
            },
        ),
    ]
